package com.routetracker.app.models

/**
 * Represents a complete recorded route with its metadata.
 * @param id Unique route identifier (auto-generated by Room)
 * @param name User-defined name for the route
 * @param date Unix timestamp when the route was created
 * @param distanceKm Total distance in kilometers (calculated via Haversine)
 * @param durationSeconds Total duration in seconds
 * @param gpxFilePath Absolute path to the GPX file on disk
 * @param averageSpeed Average speed in km/h (calculated)
 * @param maxSpeed Maximum speed in km/h (calculated)
 */
data class Route(
    val id: Long = 0,
    val name: String,
    val date: Long,
    val distanceKm: Double,
    val durationSeconds: Long,
    val gpxFilePath: String,
    val averageSpeed: Double = 0.0,
    val maxSpeed: Double = 0.0
)
